# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - which python
      - source $READTHEDOCS_VIRTUALENV_PATH/bin/activate
      - which python
      - poetry install --with docs
      - which python
      - which pip
      - poetry run which python
      - poetry run which pip
      - pip list
      - pip install structlog
      - poetry install --all-extras --with docs
      - pip list
      - poetry run pip list

sphinx:
  builder: html
  configuration: docs/source/conf.py