version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Pydiverse23
    ports:
      - "6543:5432"
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PydiQuant27
    ports:
      - "1433:1433"
  zoo:
    image: zookeeper
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: ruok
      ZOO_MAX_CLIENT_CNXNS: 100
    ports:
      - "2181:2181"
