version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pipedag
      POSTGRES_DB: pipedag
    ports:
      - 5432:5432

  zoo:
    image: zookeeper
    ports:
      - 2181:2181
