name: Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'

jobs:

  Linting:
    name: "Linting - pre-commit hooks - Python 3.8"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Linting - Run pre-commit checks
        uses: pre-commit/action@v3.0.0

  Tests:
    name: "${{ matrix.os }} / ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [Ubuntu]
        python-version: ['3.8', '3.9', '3.10']
    services:
      ibm_db2:
        image: ibmcom/db2:11.5.5.1
        env:
          LICENSE: accept
          DB2INSTANCE: db2inst1
          DB2INST1_PASSWORD: password
          DBNAME: testdb
          UPDATEAVAIL: "NO"
        options: --privileged
        ports:
          - 50000:50000
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Microsoft ODBC
        run: sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install -vvv -E mssql -E ibm_db2 --no-interaction

      - name: Start Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ./docker-compose.yaml

      - name: Wait for Docker Servers
        timeout-minutes: 1
        shell: bash
        run: |
          until bash ./.github/workflows/resources/docker_compose_ready.sh; do
            sleep 2
          done

      - name: Wait for DB/2
        timeout-minutes: 2
        run: |
          until docker logs "${{ job.services.ibm_db2.id }}" 2>&1 | grep -q "Setup has completed"; do 
            sleep 10
            echo Waiting
          done

      - name: Test
        shell: bash
        run: |
          poetry run pytest -q tests --mssql --ibm_db2
          # poetry run pytest -s tests  # interactive log output
