name: Nightly Tests

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should-run: ${{ steps.should-run.outputs.should-run }}
    steps:
      - uses: actions/checkout@v3

      - name: "check if latest commit is within 24 hrs"
        id: should-run
        continue-on-error: true
        if: ${{ github.event_name == 'schedule' }}
        shell: bash
        run: "test -z $(git rev-list --after=\"24 hours\" ${{ github.sha }}) && echo \"::set-output name=should-run::false\""

  tox_test:
    name: "Tox - ${{ matrix.os }} / ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}-latest
    needs: check
    if: ${{ needs.check.outputs.should-run != 'false' }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: [ Ubuntu ]
        python-version: [ '3.11' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          docker-services: |
            postgres
            zoo

      - name: Run Tests
        shell: bash
        run: |
          poetry run -- tox -- --workers 4 -s
