name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:
  release:
    name: 'Build and Release on PyPi'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Build and Publish
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
